### ISSUE TITLE
现阶段存在的几个bug

### ISSUE THREAD

**Issue by lilinmao** [neilleecn/DailyZHIHU#1]
BUG：
1. CertainColumnActivity 中，点击进入条目失败
2.  CertainStoryActivity 中，上方图片未在 statusBar 上进行绘制
3. 当 CertainStoryActivity 处于如下状态（ FAB 隐藏）时，action_left 点不动

TODO：
- [ ] CertainStoryActivity 中 FloatActionBar 的颜色及图标修改
- [ ] Comment Activity 的评论展示问题
- [ ] 整个主题的 Navigation 汉堡包、Menu 的三点 的颜色修改（白色）
- [ ] 优化CertainThemeActivity、CertainColumnActivity的显示
- [ ] 有必要将CardViewbgColor颜色更改掉

**Comment by cnneillee** [comment]
BUG：
- [x] CertainColumnActivity 中，点击进入条目失败
- [x] CertainStoryActivity 中，上方图片未在 statusBar 上进行绘制
- [x] 当 CertainStoryActivity 处于如下状态（ FAB 隐藏）时，action_left 点不动（这似乎不是bug，本人重复实践，并未产生）

TODO：
 - [x] CertainStoryActivity 中 FloatActionBar 的颜色及图标修改
 - [x] Comment Activity 的评论展示问题
 - [x] 整个主题的 Navigation 汉堡包、Menu 的三点 的颜色修改（白色）
 - [x] 优化CertainThemeActivity、CertainColumnActivity的显示
 - [x]  有必要将CardViewbgColor颜色更改掉
